version: '3.9'

services:
  db:
    image: postgres:15
    container_name: ozon_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  ozon_scraper:
    build:
      context: ./ozon_scraper
    container_name: ozon_scraper
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DRIVER_PATH: ${DRIVER_PATH}
      MAX_THREADS: ${MAX_THREADS}
    depends_on:
      - db

  api:
    build:
      context: ./api
    container_name: ozon_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

volumes:
  db_data:
